version: "3"
services:
  rest-assured:
    image: maven:3.9.6-eclipse-temurin-17
    volumes:
      - .:/app
    working_dir: /app
    command: bash
    ports:
      - 3000:3000
    environment:
      - GOREST_TOKEN=${GOREST_TOKEN}

